---
- name: Create LPP for clients
  hosts: nimserver 
  collections: 
    - ibm.power_aix
  vars_files:
    - "./vars/nim_master.yaml"
    - "./vars_{{ change_order }}/lpp_request.yaml"
  vars:
    cur_time: "{{ ansible_date_time.iso8601_basic_short }}"
  tasks:
  - name: Set log vars
    set_fact:
      action: nim_lpp_create
      items: ""
    run_once: true

  - name: PreCheck current user is ansiadm
    include_tasks: tasks/fail_when_not_ansiadm.yaml

  - name: Start to create LPP resources ...
    block:
    - include_tasks: tasks/log_begin.yaml

    - name: Create LPP source
      vars:
        postfixtime: "_mksysb_{{ cur_time }}"
      nim_resource:
        action: create
        name: "{{ item.key }}"
        object_type: lpp_source
        attributes:
          source: "{{ item.value.lpp_src }}"
          location: "{{ item.value.home }}"
      register: lpp_result 
      loop: "{{ lookup('dict',lpp_name,wantlist=True) }}"
      #when: inventory_hostname == nim_master.name
  
    - name: Display the result of mksysb
      debug:
        msg: "{{ lpp_result }}"

    - include_tasks: tasks/log_success.yaml
   
    rescue:
    - include_tasks: tasks/log_error.yaml
    
    always:
    - include_tasks: tasks/log_end.yaml