---
- name: alt disk 
  hosts: aix
  gather_facts: yes
  vars_files:
    - "./vars_{{ change_order }}/alt_disk_list.yaml"
  vars:
    cur_time: "{{ ansible_date_time.iso8601_basic_short }}"
  tasks:
  - name: Set log vars
    set_fact:
      action: alt_disk_list
      items: ""
    run_once: true
  
  - name: PreCheck current user is ansiadm
    include_tasks: tasks/fail_when_not_ansiadm.yaml

  - name: Start to alt disk checking ... 
    block:
    - include_tasks: tasks/log_begin.yaml
    
    - name: List the alt_disk image
      shell: |
        /usr/sbin/lsvg| grep altinst_rootvg
      register: lsalt_result
      ignore_errors: true
  
    - name: Display the result (rc=0)
      debug:
        msg: "This host contain alt rootvg disk" 
      when: lsalt_result.rc == 0

    - name: Display the result (rc=1)
      debug:
        msg: "This host DO NOT contain alt rootvg disk" 
      when: lsalt_result.rc == 1

    - name: Output alt_disk list to json logfile ./logfile/alt_disk_list.json
      copy:
        content: "{{ lsalt_result }}"
        dest: "./logfile/alt_disk_list.json"
        owner: ansiadm
        group: ansiadm
        force: yes
      delegate_to: 127.0.0.1

    - include_tasks: tasks/log_success.yaml

    rescue:
    - include_tasks: tasks/log_error.yaml

    always:
    - include_tasks: tasks/log_end.yaml