---
- name: alt disk 
  hosts: aix
  gather_facts: yes
  # vars_files:
  #  - "./vars_{{ change_order }}/altdisk_list.yaml"
  vars:
    cur_time: "{{ ansible_date_time.iso8601_basic_short }}"
  tasks:
  - name: Set log vars
    set_fact:
      action: alt_disk_list
      items: ""
    run_once: true
  
  - name: PreCheck current user is ansiadm
    include_tasks: tasks/fail_when_not_ansiadm.yaml

  - name: Start to alt disk checking ... 
    block:
    - include_tasks: tasks/log_begin.yaml

    - name: List the alt_disk image
      include_tasks: tasks/list_altdisk.yaml
    
    - include_vars:
        file: "./vars_{{ change_order }}/altdisk_list.yaml"
    
    - name: Display the existing altinst_rootvg list
      debug:
        msg: "Server: {{ item.name }} altinst_rootvg is {{ item.altdisk }}"
      when: inventory_hostname == item.name
      loop: "{{ alt_server }}"
      delegate_to: 127.0.0.1

    - include_tasks: tasks/log_success.yaml

    rescue:
    - include_tasks: tasks/log_error.yaml

    always:
    - include_tasks: tasks/log_end.yaml
