---
- name: Gather LOG files (This is nmon log as example)
  hosts: aix
  gather_facts: yes
  vars_files:
    - "./vars/nmon_path.yaml"
  #  - "./vars_{{ change_order }}/alt_disk_list.yaml"
  vars:
    cur_time: "{{ ansible_date_time.iso8601_basic_short }}"
  tasks:
  - name: Set log vars
    set_fact:
      action: gather_nmon
      items: ""
    run_once: true
  
  - name: PreCheck current user is ansiadm
    include_tasks: tasks/fail_when_not_ansiadm.yaml

  - name: Start to gather the nmon files ... 
    block:
    - include_tasks: tasks/log_begin.yaml
    
    - name: Get the file names of nmon
      find:
        paths: "{{ nmon_path.src }}"
        patterns: '*.nmon'
      #  use_regex: yes
      register: file_2_fetch

    - name: Copy file from remote to local
      fetch:
        src: "{{ item.path }}"
        dest: "./nmon_logs/"
        flat: yes
      loop: "{{ file_2_fetch.files }}"

    - include_tasks: tasks/log_success.yaml

    rescue:
    - include_tasks: tasks/log_error.yaml

    always:
    - include_tasks: tasks/log_end.yaml