---
- name: List filesystems
  hosts: all
  environment:
    PATH: "{{ extra_path }}:{{ ansible_env.PATH }}"
  tasks:
    - name: Set log vars
      set_fact:
        action: filesystems_list
        items: ""
      run_once: true

    - name: List filesystems
      block:
        - include_tasks: tasks/log_begin.yaml
        - name: List filesystems
          command: sudo -n lsfs
          register: results
        - name: List filesystems
          debug:
            msg: "{{ results.stdout_lines }}"
        - include_tasks: tasks/log_success.yaml
      rescue:
        - include_tasks: tasks/log_error.yaml
      always:
        - include_tasks: tasks/log_end.yaml

