---
- name: Add filesystems
  hosts: all
  vars_files:
    - vars_{{ change_order }}/filesystems.yaml
  environment:
    PATH: "{{ extra_path }}:{{ ansible_env.PATH }}"
  tasks:
    - set_fact:
        filesystems_add: "{{ filesystems_add | selectattr('host','==',inventory_hostname) | list  }}"

    - name: PreCheck current user is ansiadm
      include_tasks: tasks/fail_when_not_ansiadm.yaml

    - name: PreCheck parameter alert_project_code is specified
      include_tasks: tasks/fail_when_not_specify_alert_project_code.yaml
      vars:
        parameters: "{{ item }}"
      loop: "{{ filesystems_add }}"
      run_once: true
      tags: precheck

    - name: PreCheck parameter email_alert_level is specified
      include_tasks: tasks/fail_when_not_specify_email_alert_level.yaml
      vars:
        parameters: "{{ item }}"
      loop: "{{ filesystems_add }}"
      run_once: true
      tags: precheck

    - name: PreCheck parameter pager_alert_level is specified
      include_tasks: tasks/fail_when_not_specify_pager_alert_level.yaml
      vars:
        parameters: "{{ item }}"
      loop: "{{ filesystems_add }}"
      run_once: true
      tags: precheck

    - name: PreCheck the filesystems don't exist
      include_tasks: tasks/fail_when_filesystem_exist.yaml
      vars:
        filesystem_name: "{{ item.filesystem }}"
      loop: "{{ filesystems_add }}"
      tags: precheck

    - name: PreCheck the lvs don't exist
      include_tasks: tasks/fail_when_lv_exist.yaml
      vars:
        lv_name: "{{ item.lv }}"
      loop: "{{ filesystems_add }}"
      tags: precheck

    - name: PreCheck the vgs exist
      include_tasks: tasks/fail_when_vg_not_exist.yaml
      vars:
        vg_name: "{{ item.vg }}"
      loop: "{{ filesystems_add }}"
      tags: precheck

    - name: PreCheck the users exists
      include_tasks: tasks/fail_when_user_not_exist.yaml
      vars:
        user_name: "{{ item.user }}"
      loop: "{{ filesystems_add }}"
      tags: precheck

    - name: PreCheck the groups exists
      include_tasks: tasks/fail_when_group_not_exist.yaml
      vars:
        group_name: "{{ item.group }}"
      loop: "{{ filesystems_add }}"
      tags: precheck

    - name: Set log vars
      set_fact:
        action: filesystems_add
        items: "{{ filesystems_add }}"
      run_once: true

    - name: Add filesystems
      block:
        - include_tasks: tasks/log_begin.yaml
        - include_tasks: tasks/fs_add.yaml
          loop: "{{ filesystems_add }}"
        - include_tasks: tasks/log_success.yaml
      rescue:
        - include_tasks: tasks/log_error.yaml
      always:
        - include_tasks: tasks/log_end.yaml

    - name: PostCheck- verify the filesystems exist
      include_tasks: tasks/fail_when_filesystem_not_exist.yaml
      vars:
        filesystem_name: "{{ item.filesystem }}"
      loop: "{{ filesystems_add }}"
      tags: postcheck
