---
- name: List all groups
  hosts: all
  environment:
    PATH: "{{ extra_path }}:{{ ansible_env.PATH }}"
  tasks:
    - name: Set log vars
      set_fact:
        action: groups_list
        items: ""
      run_once: true

    - name: List all groups
      block:
        - include_tasks: tasks/log_begin.yaml
        - name: List all groups
          command: lsgroup ALL
          register: results
        - name: List all groups
          debug:
            msg: "{{ results.stdout_lines }}"
        - include_tasks: tasks/log_success.yaml
      rescue:
        - include_tasks: tasks/log_error.yaml
      always:
        - include_tasks: tasks/log_end.yaml

