---
- name: Show ntp conf file
  hosts: all
  environment:
    PATH: "{{ extra_path }}:{{ ansible_env.PATH }}"
  tasks:
    - name: Set log vars
      set_fact:
        action: ntp_list
        items: ""
      run_once: true

    - name: Show {{ ntp_conf_file }}
      block:
        - include_tasks: tasks/log_begin.yaml
        - name: Show {{ ntp_conf_file }}
          command: sudo -n cat -n {{ ntp_conf_file }}
          register: results
        - name: Show {{ ntp_conf_file }}
          debug:
            msg: "{{ results.stdout_lines }}"
        - include_tasks: tasks/log_success.yaml
      rescue:
        - include_tasks: tasks/log_error.yaml
      always:
        - include_tasks: tasks/log_end.yaml

