---
- name: List pvs
  hosts: all
  environment:
    PATH: "{{ extra_path }}:{{ ansible_env.PATH }}"
  tasks:
    - name: Set log vars
      set_fact:
        action: pvs_list
        items: ""
      run_once: true

    - name: List pvs
      block:
        - include_tasks: tasks/log_begin.yaml
        - name: List pvs
          shell: sudo -n lspv
          register: results
        - name: List pvs
          debug:
            msg: "{{ results.stdout_lines }}"
        - include_tasks: tasks/log_success.yaml
      rescue:
        - include_tasks: tasks/log_error.yaml
      always:
        - include_tasks: tasks/log_end.yaml

