---
- name: Change owner for raw lvs
  hosts: all
  vars_files:
    - vars_{{ change_order }}/rawlvs.yaml
  environment:
    PATH: "{{ extra_path }}:{{ ansible_env.PATH }}"
  tasks:
    - name: PreCheck current user is ansiadm
      include_tasks: tasks/fail_when_not_ansiadm.yaml

    - name: PreCheck the lvs exist
      include_tasks: tasks/fail_when_lv_not_exist.yaml
      vars:
        lv_name: "{{ item.rawlv }}"
      loop: "{{ rawlvs_chown }}"
      tags: precheck

    - name: PreCheck the users exists
      include_tasks: tasks/fail_when_user_not_exist.yaml
      vars:
        user_name: "{{ item.user }}"
      loop: "{{ rawlvs_chown }}"
      tags: precheck

    - name: PreCheck the groups exists
      include_tasks: tasks/fail_when_group_not_exist.yaml
      vars:
        group_name: "{{ item.group }}"
      loop: "{{ rawlvs_chown }}"
      tags: precheck

    - name: Set log vars
      set_fact:
        action: rawlvs_chown
        items: "{{ rawlvs_chown }}"
      run_once: true

    - name: Change owner for raw lvs
      block:
        - include_tasks: tasks/log_begin.yaml
        - name: Change owner for raw lvs
          include_tasks: tasks/rawlv_chown.yaml
          loop: "{{ rawlvs_chown }}"
        - include_tasks: tasks/log_success.yaml
      rescue:
        - include_tasks: tasks/log_error.yaml
      always:
        - include_tasks: tasks/log_end.yaml

