---
- name: Edit users
  hosts: all
  vars:
    - group_list: []
  vars_files:
    - vars_{{ change_order }}/users.yaml
  environment:
    PATH: "{{ extra_path }}:{{ ansible_env.PATH }}"
  tasks:
    - name: PreCheck current user is ansiadm
      include_tasks: tasks/fail_when_not_ansiadm.yaml
      run_once: true

    - name: PreCheck the users exists
      include_tasks: tasks/fail_when_user_not_exist.yaml
      vars:
        user_name: "{{ item.name }}"
      loop: "{{ users_edit }}"
      tags: precheck

    - set_fact:
        group_list: "{{ group_list + [ item.attributes.pgrp ] }}"
      when: item.attributes.pgrp is defined
      loop: "{{ users_edit }}"
      tags: precheck

    - set_fact:
        group_list: "{{ group_list + item.attributes.groups.split(',') }}"
      when: item.attributes.groups is defined
      loop: "{{ users_edit }}"
      tags: precheck

    - name: PreCheck the groups exist
      include_tasks: tasks/fail_when_group_not_exist.yaml
      vars:
        group_name: "{{ item }}"
      loop: "{{ group_list }}"
      tags: precheck

    - name: Set log vars
      set_fact:
        action: users_edit
        items: "{{ users_edit }}"
      run_once: true

    - name: Edit users
      block:
        - include_tasks: tasks/log_begin.yaml
        - include_tasks: tasks/user_edit.yaml
          loop: "{{ users_edit }}"
        - include_tasks: tasks/log_success.yaml
      rescue:
        - include_tasks: tasks/log_error.yaml
      always:
        - include_tasks: tasks/log_end.yaml

