- block:
    - fail:
        msg: "Only user 'ansiadm' can run this playbook. Or you can run precheck with '--tags precheck'." 
      when: lookup('env','USER') != 'ansiadm'
      delegate_to: 127.0.0.1
