- block:
    - shell: |
         sudo -n lsfs {{ filesystem_name }}
      register: results
      ignore_errors: true
      tags: 
        - precheck
        - postcheck
    - fail:
        msg: "File system {{ filesystem_name }} exists." 
      when: results.rc == 0
      tags: 
        - precheck
        - postcheck
