- block:
    - shell: |
         sudo -n lslv {{ lv_name }}
      register: results
      ignore_errors: true
      tags: 
        - precheck
        - postcheck
    - fail:
        msg: "LV {{ lv_name }} exists." 
      when: results.rc == 0
      tags: 
        - precheck
        - postcheck
