- block:
    - shell: |
         sudo -n lsuser {{ user_name }}
      register: results
      ignore_errors: true
      tags: 
        - precheck
        - postcheck
    - fail:
        msg: "User {{ user_name }} doesn't exist yet." 
      when: results.rc != 0
      tags: 
        - precheck
        - postcheck
