- block:
    - shell: |
         sudo -n ls {{ path }}
      register: results
      ignore_errors: true
      tags: 
        - precheck
        - postcheck
    - fail:
        msg: "File {{ path }} doesn't exist yet." 
      when: results.rc != 0
      tags: 
        - precheck
        - postcheck
