- block:
    - shell: |
         sudo -n lsuser ALL | grep "home={{ home }} "
      register: results
      ignore_errors: true
      tags: 
        - precheck
        - postcheck
    - fail:
        msg: "HOME {{ home }} has been used by other user already." 
      when: results.rc == 0
      tags: 
        - precheck
        - postcheck
