- block:      
    - shell: |
         sudo -n lsuser -a home {{ item.name }} |cut -d= -f 2| grep -v mail
      register: home_dir
      ignore_errors: true

    - shell: |
         sudo -n lsfs {{ home_dir.stdout }}
      register: fs_results
      ignore_errors: true
    
    - name: Unmount {{ home_dir.stdout }}
      ibm.power_aix.mount:
        state: umount
        mount_dir: "{{ home_dir.stdout }}"
        force: true
      when: fs_results.rc == 0
          
    - name: Delete user {{ item.name }}
      ibm.power_aix.user:
        state: absent
        name: "{{ item.name }}"
        remove_homedir: "true"
      register: results
      
    - name: Delete filesystem {{ home_dir.stdout }}
      ibm.power_aix.filesystem:
        state: absent
        filesystem: "{{ home_dir.stdout }}"	
      when: fs_results.rc == 0
    
    - name: "Delete {{ item.name }}'s mail and cron"
      shell: |
        sudo -n rm -f /var/spool/mail/{{ item.name }} 
        sudo -n rm -f /var/spool/cron/crontabs/{{ item.name}}
      register: results
