lines_add:
  - line_num: 2222
    ip_address: "252.165.207.111"
    host_name: "1yourhost.com yourhost"
  - line_num: 79 
    ip_address: "172.168.2.222"
    host_name: "2myhost2.com myhost2"

lines_delete:
  - 78
  - 79
